bIo9/urls.py
from django.conf.urls import url
from django.contrib.auth.views import password_reset_confirm
from .views import register, index, log_in, log_out, change_password, reset_password, set_new_password,\
					show_user_page, change_user_photo, change_user_info, post_a_blog, like_a_blog,\
					follow_a_user, make_a_comment, get_full_chat

app_name = 'bIo9'

urlpatterns = [
	url(r'^$', index, name='index'),
	#authentication
	url(r'^register/$', register, name='register'),
	url(r'^login/$', log_in, name='login'),
	url(r'^logout/$', log_out, name='logout'),
	url(r'^change_password/$', change_password, name="change_password"),
	url(r'^reset_password/$', reset_password, name="reset_password"),
	url(r'^reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, {'post_reset_redirect': 'bIo9:set_new_password', 'template_name': 'bIo9/set_new_password.html'}, name="password_reset_confirm"),
	url(r'^reset_password/set_new_password$', set_new_password, name='set_new_password'),
	#user
	url(r'^user/user_id=(?P<user_id>[1-9]+[0-9]*)/$', show_user_page, name='show_user_page'),
	url(r'^user/change_photo$', change_user_photo, name='change_user_photo'),
	url(r'^user/change_info$', change_user_info, name='change_user_info'),
	url(r'^user/post_a_blog$', post_a_blog, name='post_a_blog'),
	url(r'^user/like_a_blog$', like_a_blog, name='like_a_blog'),
	url(r'^user/follow_a_user$', follow_a_user, name='follow_a_user'),
	url(r'^user/comment/blog_id=(?P<blog_id>[1-9]+[0-9]*)$', make_a_comment, name='make_a_comment'),
	url(r'^user/comment/comment_id=(?P<comment_id>[1-9]+[0-9]*)$', get_full_chat, name='get_full_chat'),
]

bIo9/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
import re
import os

sex_choices = (('F', 'Female'),
				('M', 'Male'),
				('S', 'Secret'))

def validate_nickname(nickname):
	pattern = re.compile(r'^[a-zA-Z]+[a-zA-Z0-9]*$')
	if re.match(pattern, nickname):
		return True
	else:
		return False

def upload_to(instance, filename):
	return os.path.join(str(instance.id), filename)

class User(AbstractUser):
	nickname = models.CharField(max_length=10, blank=True, validators=((validate_nickname,)))
	sex = models.CharField(choices=sex_choices, max_length=10, default='S')
	age = models.PositiveIntegerField(default=17)
	mood = models.TextField(blank=True)
	introduction = models.TextField(blank=True)
	photo = models.ImageField(upload_to=upload_to, default='dragonCat.jpg')
	follows = models.TextField(blank=True, default='')

	class Meta(AbstractUser.Meta):
		pass


class Blog(models.Model):
	content = models.TextField(blank=True)
	update_time = models.DateTimeField(auto_now=True)
	followers = models.TextField(blank=True)
	followers_amt = models.PositiveIntegerField(default=0)
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def can_be_followed_by(self, user_id):
		return not int(user_id) in (int(x) for x in self.followers.split(';') if x != '') and int(user_id) != self.user.id


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	content = models.TextField(blank=True)
	reply_to = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
	create_time = models.DateTimeField(auto_now=True)
	my_floor = models.PositiveIntegerField(default=1)

bIo9/templates/bIo9/__blogs_in_one_page.html
{% load template_tags %}

{% for obj in cur_page %}
	<div class='one_blog'>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 one_comment_reply_to">
			<a href="{% url 'bIo9:show_user_page' obj.user.id %}" class="thumbnail tiny_photo"><img src="{{ obj.user.photo.url }}" class="photo_in_thumbnail"></a>
			<a href="{% url 'bIo9:show_user_page' obj.user.id %}" class="reply_user">{{ obj.user.nickname }}</a>
			</div>
			<div class="post_time col-lg-6 col-md-6 col-sm-6">post time  {{ obj.update_time|date:"Y-m-d H:i:s" }}</div>
		</div>
		<p class="blog_content">{{ obj.content }}</p>
		<div class="row comment_and_follow_row">
			<div class="col-lg-2 col-md-2 col-sm-2">
				{% if user.is_authenticated and obj|blog_can_be_followed:user.id %}
					<a href="javascript:void(0);" id="blog_{{ obj.id }}" onclick="like_a_blog(this)">
						<i class="fa fa-thumbs-o-up fa-lg mythumb"></i>
					</a>
				{% else %}
					<i class="fa fa-thumbs-up fa-lg mythumb"></i>
				{% endif %}
					<span>{{ obj.followers_amt }}</span>	 		
		 	</div>
		 	<div class="col-lg-2 col-md-2 col-sm-2">
		 		<a class="btn btn-reverse" href="{% url 'bIo9:make_a_comment' obj.id %}"><i class="fa fa-comment"></i> <strong>Comment({{ obj.comment_set.count }})</strong></a>
		 	</div>
		</div>
	</div>
{% endfor %}

<div class="pagination">
	{% if cur_page.has_previous %}
		<a href="?page={{ cur_page.previous_page_number }}">previous</a>
	{% endif %}
		{{ cur_page.number}}
	{% if cur_page.has_next %}
		<a href="?page={{ cur_page.next_page_number }}">next</a>
	{% endif %}
</div>

<script type="text/javascript">
	function like_a_blog(obj){
	$.ajax({
		url: "{% url 'bIo9:like_a_blog' %}",
		type: "POST",
		data: {csrfmiddlewaretoken: '{{ csrf_token }}', 
				'user_id': '{{ user.id }}',
				'ele_id': $(obj).attr('id')},
		success: function(ret_data){
			$(obj).next().text(jQuery.parseJSON(ret_data)['new_val']);
			$(obj).children().attr('class', 'fa fa-thumbs-up fa-lg mythumb')
			$(obj).parent().prepend($(obj).children())
			$(obj).remove();
		}
	});
};
</script>

bIo9/templates/bIo9/change_password.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<div class="container-fluid">
	<div class="rows">
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" id="register_zone">
			<h2><strong>Log In</strong></h2>
			<form action="{% url 'bIo9:change_password' %}" method="post" id="form_register" role="form">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{ field.label_tag }}</label>
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-primary pull-right" id="btn_register">register</button>
				<input type="hidden" name="next" value="{{ next }}" />
			</form>			
		</div>
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/change_photo.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<div class="container-fluid">
	<div class="rows">
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" id="register_zone">
			<h2><strong>Change Photo</strong></h2>
			<form action="{% url 'bIo9:change_user_photo' %}" enctype="multipart/form-data" method="post" id="form_register" role="form">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{ field.label_tag }}</label>
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-primary pull-right" id="btn_register">change</button>
				<input type="hidden" name="next" value="{{ next }}" />
			</form>			
		</div>
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/change_user_info.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<!-- include some information -->
<div class="container">
	<div class="row">
		<div id="user_photo" class="col-lg-3 col-md-3 col-sm-3">
			<a class="thumbnail user_photo_outline" href="{% url 'bIo9:change_user_photo' %}" >
				<img src="{{ user.photo.url }}" alt="user photo" class="user_photo">
			</a>
			<a href="{% url 'bIo9:show_user_page' user.id %}" class="btn btn-default" style="width: 100%;">Back to My Page</a>
		</div>
		<div class="col-lg-9 col-md-9 col-sm-9">
			<form action="{% url 'bIo9:change_user_info' %}" method="post" id="form_register" role="form">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{ field.label_tag }}</label>
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-default pull-right" id="btn_register">Change</button>
				<input type="hidden" name="next" value="{{ next }}" />
			</form>	
		</div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/email_sent.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<div class="container-fluid">
	<div class="rows">
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" id="register_zone">
			<p>Please check your email, and use the link to reset your password.</p>		
		</div>
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/full_chat.html
{% extends 'bIo9/layout.html' %}

{% block body %}
{% for comment in cur_page %}
	 				<div class="one_comment">
	 					<div class="row">
		 					<div class="col-lg-6 col-md-6 col-sm-6 one_comment_reply_to">
		 						<a href="{% url 'bIo9:show_user_page' comment.user.id %}" class="thumbnail tiny_photo"><img src="{{ comment.user.photo.url }}" class="photo_in_thumbnail"></a>
		 						<a href="{% url 'bIo9:show_user_page' comment.user.id %}" class="reply_user">{{ comment.user.nickname }}</a>
		 						{% if comment.reply_to %}
		 							 <span>reply to</span> 
		 						<a href="{% url 'bIo9:show_user_page' comment.user.id %}" class="reply_user">{{ comment.reply_to.user.nickname }}</a>
		 						{% endif %}
		 					</div>
			 				<div class="col-lg-6 col-md-6 col-sm-6 one_comment_time">
			 					floor-{{ comment.my_floor }} | reply time : {{ comment.create_time|date:'Y-m-d H:i:s' }}
			 				</div>
						</div>
	 					<div class="one_comment_content">
		 					{{ comment.content }}
		 				</div>
	 				</div>
	 			{% endfor %}
				<!-- pagination -->
				<div class="pagination">
					{% if cur_page.has_previous %}
						<a href="?page={{ cur_page.previous_page_number }}">previous</a>
					{% endif %}
						{{ cur_page.number}}
					{% if cur_page.has_next %}
						<a href="?page={{ cur_page.next_page_number }}">next</a>
					{% endif %}
				</div>
{% endblock %}

bIo9/templates/bIo9/index.html
{% extends 'bIo9/layout.html' %}

{% block body %}
	<div class="container">
		<div class="row">
			<!-- list latest blogs -->
			<div id="blog_area" class="col-lg-8 col-md-8 col-sm-8">
				<h2 class="text-center">All Blogs:</h2>
				<hr>
				{% include 'bIo9/__blogs_in_one_page.html' %}				
			</div>
			<!-- list active users -->
			<div id="user_area" class="col-lg-4 col-md-4 col-sm-4">
				<h2 class="text-center">Active Users:</h2>
				<hr>
				{% for user in users %}
					<a href="{% url 'bIo9:show_user_page' user.id %}" class="thumbnail active_user_outline">
						<img src="{{ user.photo.url }}" alt="{{ user.nickname }}" class="active_user_photo">
						<p class="user_nickname">
							{% if user.nickname %}
								{{ user.nickname }}
							{% else %}
								no nickname
							{% endif %}
						</p>
					</a>
				{% endfor %}
			</div>	
		</div>
	</div>
{% endblock %}

bIo9/templates/bIo9/layout.html
<html>
<head>
	<title>
		{% if title %}
			{{ title }}
		{% else %}
			bIo9
		{% endif %}
	</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/myjs.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/my_functions.js' %}"></script>
</head>
<body>	
	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a href="{% url 'bIo9:index' %}" class="navbar-brand" id="brand">bIo9</a>
			</div>
			<ul class="nav navbar-nav pull-right">
				{% if user.is_authenticated %}
					<li><a href="{% url 'bIo9:show_user_page' user.id %}?next={{ request.path }}" class="thumbnail" id="nav_photo_outline">
						<img src="{{ user.photo.url }}" class="img-responsive" id="nav_photo">
					</a></li>
					<li><a href="{% url 'bIo9:change_password' %}?next={{ request.path }}">Change Password</a></li>
					<li><a href="{% url 'bIo9:reset_password' %}?next={{ request.path }}">Reset Password</a></li>
					<li><a href="{% url 'bIo9:logout' %}?next={{ request.path }}">Log Out</a></li>
				{% else %}
					<li><a href="{% url 'bIo9:register' %}?next={{ request.path }}">Register</a></li>
					<li><a href="{% url 'bIo9:login' %}?next={{ request.path }}">Log In</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
	{% if messages %}
		<div class="messages" id="message_box">
			{% for message in messages %}
				<li {% if message.tags %} class="message {{ message.tags }}-message" {% endif %}>{{ message }}</li>
			{% endfor%}
		</div>
	{% endif %}
	<div class="main_area">
		{% block body %}
		{% endblock %}
	</div>
</body>
</html>

bIo9/templates/bIo9/make_a_comment.html
{% extends 'bIo9/layout.html' %}

{% load template_tags %}

{% block body %}
<div class='blog_and_comment'>
	<div class="blog_area">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 one_comment_reply_to">
			<a href="{% url 'bIo9:show_user_page' obj.user.id %}" class="thumbnail tiny_photo"><img src="{{ obj.user.photo.url }}" class="photo_in_thumbnail"></a>
			<a href="{% url 'bIo9:show_user_page' obj.user.id %}" class="reply_user">{{ obj.user.nickname }}</a>
			</div>
			<div class="post_time col-lg-6 col-md-6 col-sm-6">post time  {{ obj.update_time|date:"Y-m-d H:i:s" }}</div>
		</div>
		<div class="blog_content">{{ obj.content }}</div>
	</div>
	 	<!-- comment area -->
 	<div class="comment_area">
 		{% if cur_page|length != 0 %}
	 		<div class="display_comment">
	 			{% for comment in cur_page %}
	 				<div class="one_comment">
	 					<div class="row">
		 					<div class="col-lg-6 col-md-6 col-sm-6 one_comment_reply_to">
		 						<a href="{% url 'bIo9:show_user_page' comment.user.id %}" class="thumbnail tiny_photo"><img src="{{ comment.user.photo.url }}" class="photo_in_thumbnail"></a>
		 						<a href="{% url 'bIo9:show_user_page' comment.user.id %}" class="reply_user">{{ comment.user.nickname }}</a>
		 						{% if comment.reply_to %}
		 							 <span>reply to</span> 
		 						<a href="{% url 'bIo9:show_user_page' comment.user.id %}" class="reply_user">{{ comment.reply_to.user.nickname }}</a>
		 						{% endif %}
		 					</div>
			 				<div class="col-lg-6 col-md-6 col-sm-6 one_comment_time">
			 					floor-{{ comment.my_floor }} | reply time : {{ comment.create_time|date:'Y-m-d H:i:s' }}
			 				</div>
						</div>
	 					<div class="one_comment_content">
		 					{{ comment.content }}
		 				</div>
		 				<div class="row">
			 				{% if user.is_authenticated %}
				 				<div id='reply_link' class="col-lg-3 col-md-3 col-sm-3">
				 					<a href="javascript:void(0);" onclick="reply_a_comment({{ comment.id }}, '{{ comment.user.nickname }}')"><i class="fa fa-comment"></i>  Reply</a>
				 				</div>
			 				{% endif %}
			 				{% if not comment.reply_to is none or comment.comment_set.count != 0 %}
				 				<div class="col-lg-4 col-md-4 col-sm-4">
				 					<a href="{% url 'bIo9:get_full_chat' comment.id %}"><i class="fa fa-comments"></i> Full Chat</a>
				 				</div>
			 				{% endif %}
			 			</div>
	 				</div>
	 			{% endfor %}
				<!-- pagination -->
				<div class="pagination">
					{% if cur_page.has_previous %}
						<a href="?page={{ cur_page.previous_page_number }}">previous</a>
					{% endif %}
						{{ cur_page.number}}
					{% if cur_page.has_next %}
						<a href="?page={{ cur_page.next_page_number }}">next</a>
					{% endif %}
				</div>
		 	</div>
 		{% endif %}
		
		{%if user.is_authenticated %}
		 	<div class="make_comment">
		 		<form action="{% url 'bIo9:make_a_comment' obj.id %}" method="post" role="form" id="comment_form">
		 			{% csrf_token %}
		 			<div class="form-group">
		 				<div class="row">
		 					<div class="col-lg-10 col-md-10 col-sm-10">
				 				<textarea class="form-control comment_text" name="content" id="comment_text_input" placeholder="Your comment..." rows="1" required="required"></textarea>
				 			</div>
				 			<div class="col-lg-2 col-md-2 col-sm-2">
				 				<button type="submit" class="btn btn-default btn_comment">Submit</button>
				 				<input hidden="hidden" name="next" value="{{ request.path }}"/>
				 			</div>
		 				</div>
		 			</div>
		 		</form>
		 	</div>
	 	{% endif %}

 	</div>
	</div>
<script type="text/javascript">
	function reply_a_comment(comment_id, nickname) {
		$('#comment_text_input').focus();
		$('#comment_text_input').attr('placeholder', 'reply to '+nickname+' : ');
		$('#comment_form').append('<input hidden="hidden" name="reply_to" value="'+comment_id+'"/>');
	};
</script>
{% endblock %}

bIo9/templates/bIo9/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'bIo9:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

bIo9/templates/bIo9/post_a_blog.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<div class="container-fluid">
	<div class="rows">
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" id="register_zone">
			<h2><strong>Post a Blog</strong></h2>
			<form action="{% url 'bIo9:post_a_blog' %}" method="post" id="form_register" role="form">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-reverse pull-right" id="btn_register">Post</button>
				<input type="hidden" name="user_id" value="{{ user.id }}" />
			</form>			
		</div>
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/register.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<div class="container-fluid">
	<div class="rows">
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" id="register_zone">
			<h2><strong>Register</strong></h2>
			<form action="{% url 'bIo9:register' %}" method="post" id="form_register" role="form">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{ field.label_tag }}</label>
						{{ field }}
						<p>{{ field.help_text|safe }}</p>
						{{ field.errors }}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-primary pull-right" id="btn_register">register</button>
				<input type="hidden" name="next" value="{{ next }}" />
			</form>			
		</div>
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/set_new_password.html
{% extends 'bIo9/layout.html' %}

{% block body %}
<div class="container-fluid">
	<div class="rows">
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-lg-6 col-md-6 col-sm-8 col-xs-10" id="register_zone">
			<h2><strong>set your password</strong></h2>
			<form action="{% url 'bIo9:set_new_password' %}" method="post" id="form_register" role="form">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<label>{{ field.label_tag }}</label>
						{{ field }}
						{{ field.errors }}
					</div>
				{% endfor %}
				<button type="submit" class="btn btn-primary pull-right" id="btn_register">submit</button>
				<input type="hidden" name="next" value="{{ next }}" />
			</form>			
		</div>
		<div class="col-lg-3 col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>
{% endblock %}

bIo9/templates/bIo9/user_page.html
{% extends 'bIo9/layout.html' %}



{% block body %}
<!-- include some information -->
<div id="user_page_head" class="container">
	<div class="row">
		<div id="user_photo" class="col-lg-3 col-md-3 col-sm-3">
			{% if cur_user == user %}
				<a class="thumbnail user_photo_outline" href="{% url 'bIo9:change_user_photo' %}">
					<img src="{{ cur_user.photo.url }}" alt="user photo" class="user_photo">
				</a>
			{% else %}
				<a href="javascript:void(0);" class="thumbnail user_photo_outline" disabled>
					<img src="{{ cur_user.photo.url }}" alt="user photo" class="user_photo">
				</a>
			{% endif %}
		</div>
		<div id="user_info_area" class="col-lg-9 col-md-9 col-sm-9">
			<div class="row user_info_row">
				<div class="col-lg-4 col-md-4 col-sm-4"><label class="user_info_item">nickname:</label> {{cur_user.nickname}}</div>
				<div class="col-lg-2 col-md-2 col-sm-2"><label class="user_info_item">age:</label> {{cur_user.age}}</div>
				<div class="col-lg-2 col-md-2 col-sm-2">
					<label class="user_info_item">sex:</label> 
					{% if cur_user.sex == 'M' %}
						<i class="fa fa-mars"></i>
					{% elif cur_user.sex == 'F' %}
						<i class="fa fa-venus"></i>
					{% else %}
						<i class="fa fa-genderless"></i>
					{% endif %}
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4"><label class="user_info_item">email:</label> {{cur_user.email}}</div>
			</div>
			<div class="user_info_row">
				<label class="user_info_item">feelings:</label> {{cur_user.mood}}
			</div>
			<div class="user_info_row">
				<label class="user_info_item">introduction:</label> {{cur_user.introduction}}
			</div>
			{% if cur_user == user %}
				<div class="user_info_row">
					<a href="{% url 'bIo9:change_user_info' %}" class="btn btn-default">Change My Information</a>
				</div>
				<div class="user_info_row">
					<a href="{% url 'bIo9:post_a_blog' %}" class="btn btn-default">Post A Blog</a>
				</div>
			{% elif cur_user != user and user.is_authenticated %}
				<div class="user_info_row">
					{% if can_follow_user %}
						<a href="javascript:void(0);" class="btn btn-default" onclick="follow_a_user(this)">
							Follow
						</a>
					{%else%}
						<a href="javascript:void(0);" class="btn btn-default">Already Followed</a>
					{% endif %}
				</div>
			{% endif %}
		</div>
	</div>
</div>
<!-- include blogs and relations -->
<div class="container">
	<div class="rows">
		<div class="col-lg-9 col-md-9 col-sm-8 col-xs-10" id="blog_display_area">
			<h2 class="text-center">My Blogs:</h2>
			<hr>
			{% include 'bIo9/__blogs_in_one_page.html' %}
		</div>

		<div class="col-lg-3 col-md-3 col-sm-4 col-xs-2">
			<h2 class="text-center">My Follows:</h2>
			<hr>
			{% for user in user_follows %}
				<a href="{% url 'bIo9:show_user_page' user.id %}" class="thumbnail active_user_outline">
					<img src="{{ user.photo.url }}" class="active_user_photo">
					<p class="user_nickname">{{ user.nickname }}</p>
				</a>
			{% endfor %}
		</div>
	</div>
</div>
<script type="text/javascript">
	function follow_a_user(obj){
		$.ajax({
			url: "{% url 'bIo9:follow_a_user' %}",
			type: "POST",
			data: {csrfmiddlewaretoken: '{{ csrf_token }}', 'page_user_id': '{{ cur_user.id }}'},
			success: function(ret_data){
				$(obj).text('Already Followed');
				$(obj).removeAttr('onclick');
			}
		});
	};
</script>
{% endblock %}